Repository acts-project/backport-test, pull requests merged in 2022-08, with the labels that each got.

#17 and more
  README.md
Labels: backport-to-develop/v0.x, auto-backport

#18 and more (#17) [develop/v0.x]
  README.md
Labels: automerge

#19 make the bots dance
  .backportrc.json
  .kodiak.toml
Labels: backport-to-develop/v0.x, auto-backport, automerge

#20 make the bots dance (#19) [backport: develop/v0.x]
  .backportrc.json
  .kodiak.toml
Labels: automerge, backport

#21 Update README.md
  README.md
Labels: automerge

#22 dance update
  .backportrc.json
  .kodiak.toml
Labels: backport-to-develop/v0.x, auto-backport, automerge

#23 dance update (#22) [backport: develop/v0.x]
  .backportrc.json
  .kodiak.toml
Labels: automerge, backport

#24 Update README.md
  README.md
Labels: backport-to-develop/v0.x, auto-backport, automerge

#25 Update README.md (#24) [backport: develop/v0.x]
  README.md
Labels: automerge, backport

#26 Update more.md
  more.md
Labels: backport-to-develop/v0.x, auto-backport, automerge

#27 Update more.md (#26) [backport: develop/v0.x]
  more.md
Labels: automerge, backport

#28 Update README.md
  README.md
Labels: backport-to-develop/v0.x, auto-backport, automerge

#29 Update README.md (#28) [backport: develop/v0.x]
  README.md
Labels: automerge, backport

#30 Update more.md
  more.md
Labels: automerge, backport develop/v0.x

#32 Update more.md
  more.md
Labels: automerge, backport develop/v0.x

#33 Update more.md
  more.md
Labels: automerge, backport develop/v0.x

#34 Update more.md [backport 33 to develop/v0.x]
  more.md
Labels: automerge, backport
